### PR TITLE
cleaned up for hosted readthedocs

### PR DESCRIPTION
**Pull request by neilwillgettoit**
this should now be in the correct structure for readthedocs hosted

### CODE REVIEW

**Comment by cjcliffe** [comment]
excellent, thanks -- lets see how it goes

**Comment by cjcliffe** [comment]
looks good!

**Comment by neilwillgettoit** [comment]
That looks really nice! I wasn't sure about readthedocs before I tried this, but now that I've played with it some and have started getting the hang of it, I really like it. I'll start on other parts of the manual now.

**Comment by cjcliffe** [comment]
hah, it's looking good thanks for getting ahead 👍

**Pull request merged**
